spring:
  datasource:
    url: jdbc:mysql://192.168.100.12:3306/admin
    username: root
    password: dfS6zS*d
    db-name: admin #用来搜集数据库的所有表
    filters: mergeStat

#多数据源情况的配置
#guns:
 # muti-datasource:
 #   open: false
 #   url: jdbc:mysql://119.23.62.36:3306/guns_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
  #  username: root
 #   password: root
 #   dataSourceNames:
  #    - dataSourceGuns
  #    - dataSourceBiz


